# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: echo 'replace me with real tests!'
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: docker compose -f ./docker/compose.yml  build
  remote_build_deploy:
    machine:
      image: ubuntu-2204:edge
    steps:
      - checkout
      # Replace this with steps to deploy to users
      - run:
          name: Push Artifacts
          command: |
            scp -r ~/project/* $SSH_USER@$SSH_HOST:/home/ubuntu/frontend/stagging/
      - run:
          name: Check Docker
          command: |
            ssh $SSH_USER@$SSH_HOST 'docker --version'
      - run:
          name: Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST 'cd ~/frontend/stagging/docker && docker compose build  &&  docker compose up -d && echo done'
      - run:
          name: Clean Stagging Area
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/frontend/stagging && find . -type f ! -name '.env.local' -exec rm -r {} \; && ls -a && echo done"
workflows:
  example_deployment_flow:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main

      - remote_build_deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main