services:
  frontend:
    build: ..
    image: frontend
    container_name: frontend
    networks:
      - application-network
    ports:
      - 3000:3000
    restart: unless-stopped
    

networks:
  application-network:
    driver: bridge